name: flutter_sequencer_example
description: Demonstrates how to use the flutter_sequencer plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.13.0

  flutter_sequencer:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sfz/
    - assets/sfz/samples/
    - assets/sf2/
    - assets/wav/
