name: flutter_sequencer
version: 0.4.4
description: >-
  A Flutter plugin for sequencing audio. Use it to build sequences of notes and play them back using
  SFZ or SF2 sound fonts.
repository: https://github.com/mikeperri/flutter_sequencer

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  flutter_lints: ^6.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: com.michaeljperri.flutter_sequencer
        pluginClass: FlutterSequencerPlugin
      ios:
        pluginClass: FlutterSequencerPlugin
